### ISSUE TITLE
Bossbar disappears sometimes

### ISSUE THREAD

**Issue by koraykoska** [TigerHix/BossbarLib#1]
The Bossbar disappears sometimes if you look around in game.

**_Reference images:**_
![2015-09-10_18 59 49](https://cloud.githubusercontent.com/assets/11356621/9795112/1bd7a2be-57ef-11e5-89fd-2af7c2489eed.png)

**_Here it is not visible:**_
![2015-09-10_18 59 46](https://cloud.githubusercontent.com/assets/11356621/9795138/39f98424-57ef-11e5-80ca-b3cbed8edb76.png)
![2015-09-10_19 00 13](https://cloud.githubusercontent.com/assets/11356621/9795140/39fdec6c-57ef-11e5-9b56-e93b83a137bc.png)
![2015-09-10_19 00 20](https://cloud.githubusercontent.com/assets/11356621/9795139/39fb7f04-57ef-11e5-8d69-83e138d0bbd2.png)

**Comment by TigerHix** [comment]
It seems a client-side limitation to me. The bossbar works by spawning an invisible wither to clients in front of them, but there are certain places such that, even BossbarLib tries its best to spawn a wither in front of the player, the client simply doesn't render it.
